##### AI TECH - Akademia Innowacyjnych Zastosowań Technologii Cyfrowych. Programu Operacyjnego Polska Cyfrowa na lata 2014-2020
<hr>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center>
    <h1 style = "font-size:48px; font-weight:normal"><b>AI</b>-TECH</style></h1>
    <br>
<br>
<br>
<br>
    <h1 style = "font-size:24px; font-weight:normal">LABORATORIUM 4</style></h1>
    <h1 style = "font-size:24px">z Głębokiego przetwarzanie tekstu i mowy</style></h1>
    <h1 style = "font-size:24px">NLP z wykorzystaniem sieci GPT
2 lub GPT 3 , cz . 1</style></h1>
    <h1 style = "font-size:24px">Przemysław Rośleń</style></h1>
    <h3 style =
</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    </body>
    </html>

<center>
Projekt współfinansowany ze środków Unii Europejskiej w ramach Europejskiego Funduszu Rozwoju Regionalnego
Program Operacyjny Polska Cyfrowa na lata 2014-2020,
Oś Priorytetowa nr 3 "Cyfrowe kompetencje społeczeństwa" Działanie  nr 3.2 "Innowacyjne rozwiązania na rzecz aktywizacji cyfrowej"
Tytuł projektu:  „Akademia Innowacyjnych Zastosowań Technologii Cyfrowych (AI Tech)”
    </center>

<hr>

# Analiza struktury algorytmu generowania tekstu przez GPT-2


Niniejszy notatnik napisany jest tak, aby wyeksponować procesy tokenizacji oraz konwersji wyjścia sieci GPT-2 do postaci czytelnej dla człowieka.

In [ ]:
# Instalacja biblioteki transformers - domyślnie niestety maszyny Colaba nie posiadają jej zainstalowanej:

!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 55.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.1/311.1 kB 40.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 106.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 94.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 36.1 MB/s eta 0:00:00


In [ ]:
# Import bibliotek
from transformers import GPT2Tokenizer, TFGPT2LMHeadModel
from transformers import pipeline, set_seed
import numpy as np
import os
import tensorflow as tf

# Przydatne źródła:
# https://data-dive.com/finetune-german-gpt2-on-tpu-transformers-tensorflow-for-text-generation-of-reviews
# https://github.com/huggingface/transformers/issues/2439

# Definicja modeli:

W razie, gdy modelu nie ma na maszynie - zostanie on pobrany z serwerów firmy utrzymującej bibliotekę transformers.

In [ ]:
# Do wyboru są różne rozmiary modelu GPT-2:
# "gpt2"
# "gpt2-medium"
# "gpt2-large"
# "gpt2-xl"
# "distilgpt2" - wersja kompaktowa uzyskana w wyniku procesu tzw. destylacji wiedzy

model     = TFGPT2LMHeadModel.from_pretrained("gpt2")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

In [ ]:
tokenizer.save_vocabulary('.')

('./vocab.json', './merges.txt')

# Przetwarzanie tekstu

In [ ]:
# Tekst do przetworzenia przez wybraną wersję sieci GPT-2
text = "What is the answer to life, the universe, and everything?"

# Tokenizacja tekstu wejściowego
encoded_input     = tokenizer(text, padding=False, add_special_tokens=False, return_tensors='tf')

print('encoded_input:')
print(encoded_input)

# Opcja do_sample powoduje, że następne słowa są wybierane losowo na podstawie rozkładu prawdopodobieństwa zwróconego przez
# sieć neuronową - ciekawy efekt można zaobserwować gdy tę losowość wyłączyt się ustawiając do_sample na False.
tokenized_outputs = model.generate(input_ids=encoded_input['input_ids'], max_length = 100, do_sample=True)

print(f'tokenized_outputs')
print(tokenized_outputs)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


encoded_input:
{'input_ids': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=
array([[2061,  318,  262, 3280,  284, 1204,   11,  262, 6881,   11,  290,
        2279,   30]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}
tokenized_outputs
tf.Tensor(
[[ 2061   318   262  3280   284  1204    11   262  6881    11   290  2279
     30   921   423  7147  1204    11   290   674 13532   423  2957   514
    612    13   887   644   286  1842    11   286  1842   290  1842    30
   6350   561 12157  6486    11   284  4691   534   898  5353    11   290
   2251 12157    30  3894  1399   810   561  1793  1842    30  1867   338
    534  3572    30   198   198  1639   743  3505    25   618   356   651
    477   428  1978    11   356  1183  2245  3612   546  1123   584    13
    775  1183  2245  2045   379   674  2460   290  4172   355  2147   517
    621   326    13   775]], shape=(1, 100), dtype=int32)
Odpowi

In [ ]:
# Dekodowanie wyjścia z modelu.
decoded_answer    = tokenizer.decode(tokenized_outputs[0],
                            skip_special_tokens=True,
                            clean_up_tokenization_spaces=True)

print("Odpowiedź modelu:")
print(decoded_answer)
print(len(decoded_answer.split(' ')))

Odpowiedź modelu:
What is the answer to life, the universe, and everything? You have chosen life, and our paths have led us there. But what of love, of love and love? Where would happiness lie, to serve your own interests, and create happiness? Well… where would God love? What's your choice?

You may remember: when we get all this together, we'll stop thinking about each other. We'll stop looking at our friends and families as nothing more than that. We
77


In [ ]:
# Dekodowanie wyjścia z modelu.
decoded_answer    = tokenizer.decode(tokenized_outputs[0][0:8],
                            skip_special_tokens=True,
                            clean_up_tokenization_spaces=True)

print("Odpowiedź modelu:")
print(decoded_answer)

Odpowiedź modelu:
What is the answer to life, the
7
